authoritative;
ddns-update-style interim;
allow booting;
allow bootp;
allow unknown-clients;
ignore client-updates;
default-lease-time 14400;
max-lease-time 14400;

subnet 10.9.8.0 netmask 255.255.255.0 {
 option routers                  10.9.8.1; # lan
 option subnet-mask              255.255.255.0;
 option domain-name              "kubelabs.com";
 option domain-name-servers       10.9.8.1;
 range 10.9.8.09 10.9.8.50;
}

host bootstrap.kubelabs.com {
 hardware ethernet 00:50:56:3D:59:27;
 fixed-address 10.9.8.10;
}

host master01.kubelabs.com {
 hardware ethernet 00:50:56:3D:98:29;
 fixed-address 10.9.8.11;
}

host master02.kubelabs.com {
 hardware ethernet 00:50:56:39:E8:22;
 fixed-address 10.9.8.12;
}

host master03.kubelabs.com {
 hardware ethernet 00:50:56:28:BC:4D;
 fixed-address 10.9.8.13;
}

host worker01.kubelabs.com {
 hardware ethernet 00:50:56:3E:0D:51;
 fixed-address 10.9.8.21;
}

host worker02.kubelabs.com {
 hardware ethernet 00:50:56:3F:C3:FD;
 fixed-address 10.9.8.22;
}
