apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: ./oc-mirror-workspace-cnv

mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
    packages:

    - name: kubevirt-hyperconverged
      channels:
      - name: stable
        minVersion: 4.18.17
        maxVersion: 4.18.17

